name: sharding-repl-cache
version: '3.8'

services:
  config-srv1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: config-srv1
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - config-data-1:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  config-srv2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: config-srv2
    restart: always
    ports:
      - "27018:27017"
    networks:
      - app-network
    volumes:
      - config-data-2:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  config-srv3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: config-srv3
    restart: always
    ports:
      - "27019:27017"
    networks:
      - app-network
    volumes:
      - config-data-3:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1-node1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node1
    restart: always
    ports:
      - "27020:27018"
    networks:
      - app-network
    volumes:
      - shard1-data-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1-node2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node2
    restart: always
    ports:
      - "27021:27018"
    networks:
      - app-network
    volumes:
      - shard1-data-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard1-node3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1-node3
    restart: always
    ports:
      - "27022:27018"
    networks:
      - app-network
    volumes:
      - shard1-data-3:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard1",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2-node1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node1
    restart: always
    ports:
      - "27023:27019"
    networks:
      - app-network
    volumes:
      - shard2-data-1:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2-node2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node2
    restart: always
    ports:
      - "27024:27019"
    networks:
      - app-network
    volumes:
      - shard2-data-2:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  shard2-node3:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2-node3
    restart: always
    ports:
      - "27025:27019"
    networks:
      - app-network
    volumes:
      - shard2-data-3:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "shard2",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s

  mongos-router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos-router
    restart: always
    ports:
      - "27026:27020"
    networks:
      - app-network
    command:
      [
        "mongos",
        "--configdb",
        "config_server/config-srv1:27017,config-srv2:27017,config-srv3:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      config-srv1:
        condition: service_healthy
      config-srv2:
        condition: service_healthy
      config-srv3:
        condition: service_healthy
      shard1-node1:
        condition: service_healthy
      shard1-node2:
        condition: service_healthy
      shard1-node3:
        condition: service_healthy
      shard2-node1:
        condition: service_healthy
      shard2-node2:
        condition: service_healthy
      shard2-node3:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      start_period: 10s
  redis_1:
    image: "redis:latest"
    container_name: redis_1
    ports:
      - "6379"
    volumes:
      - redis_1_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis_2:
    image: "redis:latest"
    container_name: redis_2
    ports:
      - "6379"
    volumes:
      - redis_2_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis_3:
    image: "redis:latest"
    container_name: redis_3
    ports:
      - "6379"
    volumes:
      - redis_3_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis_4:
    image: "redis:latest"
    container_name: redis_4
    ports:
      - "6379"
    volumes:
      - redis_4_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis_5:
    image: "redis:latest"
    container_name: redis_5
    ports:
      - "6379"
    volumes:
      - redis_5_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  redis_6:
    image: "redis:latest"
    container_name: redis_6
    ports:
      - "6379"
    volumes:
      - redis_6_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - app-network

  pymongo_api:
    container_name: pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    depends_on:
      mongos-router:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      MONGODB_URL: "mongodb://mongos-router:27020"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_1:6379"
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  config-data-1:
  config-data-2:
  config-data-3:
  shard1-data-1:
  shard1-data-2:
  shard1-data-3:
  shard2-data-1:
  shard2-data-2:
  shard2-data-3:
  redis_1_data:
  redis_2_data:
  redis_3_data:
  redis_4_data:
  redis_5_data:
  redis_6_data:
